### ISSUE TITLE
ubuntu 18.04 updated libgdal-dev to 2.4.0, and this caused pygdal==2.4.0.6 to crash 

### ISSUE THREAD

**Issue by williamvanderkamp** [nextgis/pygdal#47]
The latest ubuntu 18.04 system updates included upgrading libgdal-dev from 2.3.2 to 2.4.0.

Pygdal 2.4.0.6 installs without errors.

But this code snippet fails:
```
from django.contrib.gis import geos
p = geos.Polygon([[0,0], [0,1], [1,1], [0,0]], srid=4326)
p.json
```
The error is:
```
GDAL_ERROR 4: b'Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 381, in json
    return self.ogr.json
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 423, in ogr
    return gdal.OGRGeometry(self._ogr_ptr(), self.srs)
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 430, in srs
    return gdal.SpatialReference(self.srid)
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/gdal/srs.py", line 92, in __init__
    self.import_epsg(srs_input)
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/gdal/srs.py", line 277, in import_epsg
    capi.from_epsg(self.ptr, epsg)
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/errcheck.py", line 118, in check_errcode
    check_err(result, cpl=cpl)
  File "/home/wsv759/vcs_projects/SPLIT/venv/lib/python3.6/site-packages/django/contrib/gis/gdal/error.py", line 59, in check_err
    raise e(msg)
django.contrib.gis.gdal.error.GDALException: OGR failure.

```
The key line is the first line before the traceback. The traceback is django-related and probably not relevant. Apologies that I am using Django's geos -- I'm sure there's a simpler library that could reproduce the same problem. But I believe this could be a problem with pygdal.

**Comment by williamvanderkamp** [comment]
On second thought this could actually be a problem with libgdal-dev 2.4.0, and not pygdal. However I'm not sure how to investigate that properly.

**Comment by williamvanderkamp** [comment]
NVM -- i hadn't updated libgdal-dev appropriately. Everything now works, at libgdal-dev 3.0.2.
