### ISSUE TITLE
gdal.Info does not check for None with option format='json'

### ISSUE THREAD

**Issue by PROgram52bc** [nextgis/pygdal#71]
`None` is returned by `gdal.Info` if the argument is invalid.
```python
> info = gdal.Info("not_a_tiff_file.tif")
None
```
However, an exception is thrown when the `format='json'` option is specified. I think some error-checking should be done to prevent the error from percolating.
```python
> info = gdal.Info("not_a_tiff_file.tif", format="json")
TypeError                                 Traceback (most recent call last)
<ipython-input-18-fe27f614a6ef> in <module>
----> 1 info = gdal.Info("nonexisting", format='json')
      2 print(info)

/apps/share64/debian7/anaconda/anaconda-6/envs/qgis/lib/python3.8/site-packages/osgeo/gdal.py in Info(ds, **kwargs)
    270     if format == 'json' and deserialize:
    271         import json
--> 272         ret = json.loads(ret)
    273     return ret
    274 

/apps/share64/debian7/anaconda/anaconda-6/envs/qgis/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    339     else:
    340         if not isinstance(s, (bytes, bytearray)):
--> 341             raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    342                             f'not {s.__class__.__name__}')
    343         s = s.decode(detect_encoding(s), 'surrogatepass')

TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by dezhin** [comment]
Hi, pygdal is just a convenient way to install GDAL bindings into a virtualenv. I don't think that it's a packaging issue. But if you think so, could you try to do the same with the original system-wide installed GDAL bindings? I think the result will be the same. Otherwise, let us know.

**Comment by drnextgis** [comment]
This is not a pygdal issue and should be reported to [gdal](https://github.com/osgeo/gdal):
```
$ docker run --rm -it osgeo/gdal:ubuntu-full-3.3.2 bash
root@6b6853a227bd:/# touch 1.txt
root@6b6853a227bd:/# python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> info = gdal.Info("1.txt", format="json")
ERROR 4: `1.txt' not recognized as a supported file format.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 281, in Info
    ret = json.loads(ret)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by PROgram52bc** [comment]
Right. I see that gdal prints an error message (`ERROR 4: `1.txt' not recognized as a supported file format`) when the request file does not exist. But the `TypeError` exception is thrown from the pygdal library rather than the gdal package (e.g. /usr/lib/python3/dist-packages/osgeo/gdal.py).

Specifically, when we don't specify the `format='json'`, we don't get the exception
```python
>>> a = gdal.Info("text")
ERROR 4: text: No such file or directory
```

While we include the `format='json'` option, we get a `TypeError` exception.
```python
>>> a = gdal.Info("text", format='json')
ERROR 4: text: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 281, in Info
    ret = json.loads(ret)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
The reason we get the `TypeError` is essentially because we are trying to use `json.loads` to load a `None` object in line 281 of gdal.py. 

#73 demonstrates what a potential fix might be.
